### PR TITLE
Add stop-words for GTD

### PR DESCRIPTION
**Pull request by yanyaoer**

### CODE REVIEW

**Review by sawhney17 — CHANGES_REQUESTED** [review]
Awesome. Thanks for the PR! Any reason by you chose to use .name and then convert it to uppercase? Just take the originalName instead of name and it should be uppercase by default.

**Comment by yanyaoer** [comment]
> Awesome. Thanks for the PR! Any reason by you chose to use .name and then convert it to uppercase? Just take the originalName instead of name and it should be uppercase by default.

compare with uppercase make it work correct, even logseq.app change the originalName's output

**Comment by sawhney17** [comment]
Looks good. Just add DOING, etc to the list and we should be good to go.

**Comment by robotii** [comment]
Hi,

I have similar functionality available in my PR #6 

Would you be open to working with that to get the default list correct? I have made it a configuration option, so the user can add their own list of stop words.

The default configuration is found at https://github.com/robotii/logseq-automatic-linker/blob/feature/link-as-tags/index.ts#L50

**Comment by sawhney17** [comment]
Thank you for your contribution, I have however chosen to merge @robbotii's implementation as that was a bit more robust and customizable. Thank you nonetheless!

**Pull request closed without merging**
