### PR TITLE
test: add tests to avoid regressions

### PR DESCRIPTION
**Pull request by andreoliwa**
⚠️ Depends on this other pull request to be merged first: https://github.com/sawhney17/logseq-automatic-linker/pull/30 ⚠️ 

- add Jest and dependencies
- use console.debug() instead of log() in most places
- disable console.debug() on Jest
- format code with Prettier

### CODE REVIEW

**Comment by sawhney17** [comment]
Looks very cool! Don't have experience myself with testing especially with a logseq plug-in which makes this especially interesting to me. I guess we could run the tests through a GitHub workflow as well for PRs correct?

**Comment by andreoliwa** [comment]
> I guess we could run the tests through a GitHub workflow as well for PRs correct?

Yes.
I don't know how to do that with TypeScript projects that's why I didn't do it here...

> Looks very cool! Don't have experience myself with testing especially with a logseq plug-in which makes this especially interesting to me

I tried to isolate the function that actually does the parsing/replacement to use unit tests.
It's a good start, in my opinion.
I also don't know how to mock Logseq if we would need to use it in tests.

**Comment by andreoliwa** [comment]
> I guess we could run the tests through a GitHub workflow as well for PRs correct?

I just added a workflow to run the tests on GitHub Actions.

**Comment by sawhney17** [comment]
awesome. Merging now!

**Pull request merged**
